# Generated by Django 4.1.7 on 2023-02-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='measure_id',
            new_name='measure',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='measureunit',
            old_name='product_id',
            new_name='product',
        ),
    ]
