# Generated by Django 4.1.7 on 2023-02-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_user_id_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Amount products'),
        ),
    ]
